### ISSUE TITLE
maby a typo at here

### ISSUE THREAD

**Issue by chubbyerror** [WittBulter/sendAlert#3]
sendAlert.js
<--------------------undef tet
      if (Array.isArray(tet)) {
        sendAlertDOM.content.classList.remove('title')
        sendAlertDOM.title.innerHTML = txt[0]
        sendAlertDOM.detail.innerHTML = txt[1]
        return open()
      }

**Comment by WittBulter** [comment]
thx, in fixing.

**Comment by chubbyerror** [comment]
维特大佬对我说thx了我好激动啊啊啊（肥宅激动.gif
